name: Build and Test

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Verify secrets
        run: echo "Loaded .env"
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}

      - name: Build project
        run: yarn build
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
